from selenium import webdriver
from time import sleep
from selenium.webdriver.common.by import By

driver_obj = webdriver.Chrome()
driver_obj.get("https://www.letskodeit.com/practice")
driver_obj.maximize_window()
# driver_obj.find_element(By.XPATH,"//input[@id='bmwradio']").click()                                                            sleep(5)
driver_obj.find_element(By.XPATH, "//input[@id='benzradio']").click()
sleep(5)
driver_obj.find_element(By.XPATH, "//input[@id='hondaradio']").click()
sleep(5)
driver_obj.find_element(By.XPATH, "//input[@id='bmwcheck']").click()
sleep(5)
driver_obj.find_element(By.XPATH, "//input[@id='benzcheck']").click()
sleep(5)
driver_obj.find_element(By.XPATH, "//input[@id='hondacheck']").click()
sleep(5)
# driver_obj.find_element(By.XPATH,"//button[@id='openwindow']").click()
# #sleep(5)
# #driver_obj.find_element(By.XPATH,"//c[@id='opentab']").click()
# #sleep(5)
driver_obj.find_element(By.XPATH, "//select[@id='carselect']").click()
driver_obj.select_by_visible_text()
sleep(5)
driver_obj.find_element(By.XPATH, "//select[@id='multiple-select-example']").click()
sleep(5)
driver_obj.find_element(By.XPATH, "//input[@id='autosuggest']").click()
sleep(5)
driver_obj.find_element(By.XPATH, "//input[@id='enabled-example-input']").click()
sleep(5)
driver_obj.find_element(By.XPATH, "//input[@id='bmwradio']").click()
sleep(2)
driver_obj.find_element(By.XPATH, "//input[@id='enabled-button']").click()
sleep(2)
driver_obj.find_element(By.XPATH, "//input[@id='displayed-text']").click()
sleep()
driver_obj.find_element(By.XPATH, "//input[@id='hide-textbox']").click()
sleep(2)
driver_obj.find_element(By.XPATH, "//input[@id='show-textbox']").click()
sleep(2)
driver_obj.find_element(By.XPATH, "//input[@id='name']").send_keys('venu')
sleep(5)
driver_obj.find_element(By.XPATH, "//input[@id='alertbtn']").click()
sleep(2)
driver_obj.forward()
driver_obj.find_element(By.XPATH, "//input[@id='confirmbtn']").click()
sleep(2)
res = driver_obj.find_element(By.XPATH, "//button[@id='mousehover'").click()
sleep(2)
